# Generated by Django 3.2.9 on 2022-02-14 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20220214_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(blank=True, default='static/recursos/img/img_empty.jpg', null=True, upload_to='product/%Y/%m/%d'),
        ),
    ]
