# Generated by Django 3.2.9 on 2022-02-26 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0013_auto_20220224_2306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-fecha_creada']},
        ),
    ]
