# Generated by Django 3.2.9 on 2022-03-04 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0016_alter_descuento_prducto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descuento',
            old_name='prducto',
            new_name='producto',
        ),
    ]
