# Generated by Django 3.2.9 on 2022-02-16 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_alter_inventario_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_creada',
            field=models.DateTimeField(auto_now_add=True, default='2012-12-12'),
            preserve_default=False,
        ),
    ]
