# Generated by Django 3.2.9 on 2022-03-04 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0015_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuento',
            name='prducto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producto_descuento', to='inventario.producto'),
        ),
    ]
