# Generated by Django 3.2.9 on 2022-03-04 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0017_rename_prducto_descuento_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuento',
            name='producto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producto_descuento', to='inventario.producto'),
        ),
    ]
