# Generated by Django 4.0.3 on 2022-04-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0019_alter_descuento_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='image_test',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
