# Generated by Django 4.0.3 on 2024-02-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0020_producto_image_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_creada',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
