# Generated by Django 4.0.3 on 2024-03-13 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0021_alter_producto_fecha_creada'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='categoria',
            new_name='category',
        ),
    ]
