# Generated by Django 4.0.3 on 2024-03-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0022_rename_categoria_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d')),
                ('image_test', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveField(
            model_name='producto',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='category',
        ),
        migrations.RemoveField(
            model_name='descuento',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='producto',
        ),
    ]
