# Generated by Django 4.0.3 on 2024-03-13 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0023_product_remove_producto_autor_and_more'),
        ('venta', '0021_remove_registroventa_producto_registroventa_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.category'),
        ),
        migrations.AddField(
            model_name='descuento',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descuento', to='inventario.product'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventario_product', to='inventario.product'),
        ),
    ]
