# Generated by Django 3.2.9 on 2022-02-07 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_datosenvio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='datosEnvio',
        ),
    ]
