# Generated by Django 3.2.9 on 2022-02-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0007_auto_20220216_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroventa',
            options={'ordering': ['-fecha_creada']},
        ),
        migrations.AddField(
            model_name='datosenvio',
            name='fecha_creada',
            field=models.DateTimeField(auto_now_add=True, default="2022-12-12"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datosenvio',
            name='fecha_envio',
            field=models.DateTimeField(default="2022-12-12"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datospago',
            name='fecha_creada',
            field=models.DateTimeField(auto_now_add=True, default="2022-12-12"),
            preserve_default=False,
        ),
    ]
