# Generated by Django 3.2.9 on 2022-02-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0008_auto_20220216_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroventa',
            name='total',
            field=models.IntegerField(default=1),
        ),
    ]
