# Generated by Django 3.2.9 on 2022-02-17 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0012_alter_inventario_producto'),
        ('venta', '0010_registroventa_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroventa',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venta_producto', to='inventario.producto'),
        ),
    ]
