# Generated by Django 3.2.9 on 2022-02-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0012_alter_datosenvio_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroventa',
            name='fecha_cierre',
            field=models.DateTimeField(default='2022-12-12'),
            preserve_default=False,
        ),
    ]
