# Generated by Django 3.2.9 on 2022-03-04 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0015_alter_registroventa_fecha_cierre'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroventa',
            name='descuento',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
