# Generated by Django 4.0.3 on 2024-03-13 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0023_product_remove_producto_autor_and_more'),
        ('venta', '0020_alter_datosenvio_fecha_envio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroventa',
            name='producto',
        ),
        migrations.AddField(
            model_name='registroventa',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venta_product', to='inventario.product'),
        ),
    ]
