# Generated by Django 3.2.9 on 2022-02-07 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datosenvio',
            name='venta',
        ),
    ]
