# Generated by Django 3.2.9 on 2022-02-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_datosenvio_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosenvio',
            name='cedula',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='datosenvio',
            name='direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='datosenvio',
            name='nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='datosenvio',
            name='nroEncomienda',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='datosenvio',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
