# Generated by Django 3.2.9 on 2022-02-09 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_auto_20220208_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='datosPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nroRef', models.CharField(blank=True, max_length=200, null=True)),
                ('recibo', models.FileField(blank=True, null=True, upload_to='recibos/')),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='venta.registroventa')),
            ],
        ),
    ]
