# Generated by Django 3.2.9 on 2022-02-16 21:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0006_auto_20220216_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroventa',
            name='fecha_creada',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datospago',
            name='fecha_pago',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datospago',
            name='nroRef',
            field=models.CharField(default=datetime.datetime(2022, 2, 16, 21, 30, 22, 385654, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datospago',
            name='recibo',
            field=models.FileField(default=1988, upload_to='recibos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registroventa',
            name='estado_operacion',
            field=models.ForeignKey(default=1993, on_delete=django.db.models.deletion.CASCADE, to='venta.estadooperacion'),
            preserve_default=False,
        ),
    ]
