# Generated by Django 3.2.9 on 2022-02-24 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0011_alter_registroventa_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosenvio',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='venta_datosEnvio', to='venta.registroventa'),
        ),
    ]
