# Generated by Django 3.2.9 on 2022-03-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0016_registroventa_descuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroventa',
            name='total',
            field=models.FloatField(default=1),
        ),
    ]
