# Generated by Django 3.2.9 on 2022-03-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0017_alter_registroventa_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroventa',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
