# Generated by Django 3.2.9 on 2022-03-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0018_registroventa_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosenvio',
            name='nroEncomienda',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
