# Generated by Django 3.2.9 on 2022-03-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0019_alter_datosenvio_nroencomienda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosenvio',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
